### ISSUE TITLE
'Disable "close windows when quitting an app"' is set to the opposite

### ISSUE THREAD

**Issue by jimratliff** [rodionovd/dotfiles#2]
`# Disable "close windows when quitting an app"
defaults write NSGlobalDomain NSQuitAlwaysKeepsWindows -bool false`

In osx.sh, your comment says that your setting disables "close windows when quitting an app", but it seems to me that your setting actually ENABLES this (rather than DISABLES this).

My experimentation with changing the "Close windows when quitting an app" setting in the General preferences pane, and then performing a "defaults read -g NSQuitAlwaysKeepsWindows" shows that the value of NSQuitAlwaysKeepsWindows should be the opposite of the checkmark setting. Specifically:
When NSQuitAlwaysKeepsWindows=0, the "Close windows…" checkbox is CHECKED.
When NSQuitAlwaysKeepsWindows=1, the "Close windows…" checkbox is UN-checked.

This inverse behavior is consistent with the wordings of the checkbox setting and the defaults write key name: "Close windows…" is the opposite of "KeepsWindows".

**Comment by rodionovd** [comment]
Ooops this one is definitely a typo! Thank you for the research, gonna fix it right now 👍🏼

P.S. I mean, all this «Close windows» checkbox vs «KeepsWindows» setting is really misleading…
